### ISSUE TITLE
Cyo/Nimskull fails to compile on Termux, aarch64, due to issues with glob

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [nim-works/nimskull#417]
### Output
I have cloned the repo from the latest GitHub commit.
I used multiple variations of `CFLAGS=-landroid-glob ./koch.py boot`, such as `./koch.py boot`, `./koch.py boot -l:android-glob`, `./koch.py boot -passL=-landroid-glob` and `./koch.py boot -passl:-landroid-glob`.

```nim
u0_a347@localhost ~/nimskull (devel)> CFLAGS=-landroid-glob ./koch.py boot
Building koch.nim
Bootstrap compiler /data/data/com.termux/files/home/nimskull/build/csources/bin/nim-c181c28ae63be7c40cd316eb6744a01561617b6a not found, building
Fetching bootstrap compiler source
Running: ['git', 'clone', '--depth=1', '--single-branch', 'https://github.com/nim-works/csources_v1.git', '/data/data/com.termux/files/home/nimskull/build/csources']
Cloning into '/data/data/com.termux/files/home/nimskull/build/csources'...
remote: Enumerating objects: 2110, done.
remote: Counting objects: 100% (2110/2110), done.
remote: Compressing objects: 100% (191/191), done.
remote: Total 2110 (delta 1980), reused 2004 (delta 1916), pack-reused 0
Receiving objects: 100% (2110/2110), 4.20 MiB | 6.96 MiB/s, done.
Resolving deltas: 100% (1980/1980), done.
Updating files: 100% (8963/8963), done.
Running: ['make', '-s', '-C', '/data/data/com.termux/files/home/nimskull/build/csources', '-j', '8']
ld.lld: error: undefined symbol: glob
>>> referenced by @moptions.nim.c
>>>               c_code/2_17/@moptions.nim.o:(getNimbleFile_options_4124)
>>> referenced by @mextccomp.nim.c
>>>               c_code/2_17/@mextccomp.nim.o:(callCCompiler_extccomp_1243)
>>> referenced by @mnimblecmd.nim.c
>>>               c_code/2_17/@mnimblecmd.nim.o:(addNimblePath_nimblecmd_2053)
>>> referenced 1 more times

ld.lld: error: undefined symbol: globfree
>>> referenced by @moptions.nim.c
>>>               c_code/2_17/@moptions.nim.o:(getNimbleFile_options_4124)
>>> referenced by @moptions.nim.c
>>>               c_code/2_17/@moptions.nim.o:(getNimbleFile_options_4124)
>>> referenced by @mextccomp.nim.c
>>>               c_code/2_17/@mextccomp.nim.o:(callCCompiler_extccomp_1243)
>>> referenced 2 more times
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [makefile:885: bin/nim] Error 1
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/nimskull/./koch.py", line 278, in <module>
    main()
  File "/data/data/com.termux/files/home/nimskull/./koch.py", line 253, in main
    bootstrap.run(
  File "/data/data/com.termux/files/home/nimskull/./koch.py", line 226, in run
    self.build()
  File "/data/data/com.termux/files/home/nimskull/./koch.py", line 209, in build
    run(makeprg, "-s", "-C", Bootstrap.Source, "-j", cpus)
  File "/data/data/com.termux/files/home/nimskull/./koch.py", line 48, in run
    completed = subprocess.run(run_args, check=(not replace), cwd=cwd)
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', '-s', '-C', '/data/data/com.termux/files/home/nimskull/build/csources', '-j', '8']' returned non-zero exit status 2.
```

### Expected Output
The compiler should compile successfully, giving me the binaries for Cyo/Nimskull

### Possible Solution
I've tried many ways of passing `-landroid-glob` to the C compiler but all ways i have tried, have failed.

### Additional Information
Leorize seems to be able to compile Nimskull on Termux for himself, and the outputted binaries run on my Termux installation, but I am unable to build the Nimskull repo itself.

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Another thing I've tried was exporting CFLAGS, setting the value to `-landroid-glob`, which still didn't work
